# Server configuration
server.port=8080
app.server.url=http://localhost:8080

# Database Configuration (MySQL)
#spring.datasource.url=jdbc:mysql://localhost:3306/scheduled_messaging?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=GopiChand@26
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Database Configuration (PostgreSQL - Render)
spring.datasource.url=jdbc:postgresql://dpg-d8ili6ddt1ts73fg2ndg-a.ohio-postgres.render.com:5432/scheduledmessaging
spring.datasource.username=scheduledmessaging_user
spring.datasource.password=QR3jzMC5P2SahlMCEO1rjjLXTTCzIJR8
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.scheduler.instanceName=ScheduledMessagingScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.threadPool.threadCount=5
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=false

## JPA/Hibernate Config
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#//spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## SQL Init (Run schema.sql to initialize missing tables)
##spring.sql.init.mode=always
##spring.sql.init.continue-on-error=true
#
#
## Quartz Configuration
#spring.quartz.job-store-type=jdbc
#spring.quartz.jdbc.initialize-schema=always
#spring.quartz.properties.org.quartz.scheduler.instanceName=ScheduledMessagingScheduler
#spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
#spring.quartz.properties.org.quartz.threadPool.threadCount=5
#spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
#spring.quartz.properties.org.quartz.jobStore.isClustered=false

# File Storage Configuration (Local by default, toggle to 's3' for production)
app.storage.type=local
app.storage.local-dir=uploads

# AWS Config (Used if app.storage.type=s3)
app.aws.credentials.access-key=YOUR_ACCESS_KEY
app.aws.credentials.secret-key=YOUR_SECRET_KEY
app.aws.region=us-east-1
app.aws.s3.bucket-name=your-s3-bucket

# JWT Security parameters
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=86400000

# Mail Configuration (Using Mailpit for local interception)
spring.mail.host=127.0.0.1
#spring.mail.host=https://mailpit-vqui.onrender.com
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=587
#spring.mail.username=Geethika Bodapati
#spring.mail.password=GopiChand@26

#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
