ALTER TABLE contacts ADD COLUMN unblock_count INT NOT NULL DEFAULT 0;
ALTER TABLE contacts ADD COLUMN custom_name VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE users ADD COLUMN last_seen DATETIME NULL DEFAULT NULL;
ALTER TABLE messages ADD COLUMN reply_to_message_id BIGINT NULL DEFAULT NULL;
ALTER TABLE messages ADD CONSTRAINT fk_messages_reply_to FOREIGN KEY (reply_to_message_id) REFERENCES messages(id) ON DELETE SET NULL;
